# ローカル開発用 secrets.toml
# このファイルは .gitignore に追加して絶対に GitHub へ push しないこと！
# Streamlit Cloud 本番用は、ダッシュボード上の「Secrets」欄に同じ内容を貼り付ける

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1hlLDLrqF8lqid7Nml772c6gbG9TXq0demGFWkZg6juE/edit?gid=1661220406#gid=1661220406"
type = "service_account"
project_id = "storestocks"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN RSA PRIVATE KEY-----\nYOUR_KEY_HERE\n-----END RSA PRIVATE KEY-----\n"
client_email = "your-service-account@your-project.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
